### ISSUE TITLE
Sometimes remove(close) button is not working

### ISSUE THREAD

**Issue by starrybleu** [ctxhou/react-tabtab#116]
Hello,

I have tested remove(close) buttons on your demo site, `https://ctxhou.github.io/react-tabtab/#add-close`.

When I intentionally clicked remove buttons in tabs again and again, sometimes nothing happened.

That's it. Is there a possibility to fix it ?

**Comment by ctxhou** [comment]
@starrybleu could you provide your browser version? I tested it again and I didn't happen to me.

**Comment by ctxhou** [comment]
I've also used Chrome. If you met the same bug next time, could you paste the error message in the console?

It would be easier for the community to find the bug : )
Thank you

**Comment by starrybleu** [comment]
Unfortunately, there was not any message or log in the console.

However, I attached an image how and what I did.

![image](https://user-images.githubusercontent.com/14271094/47625904-74a8c000-db6b-11e8-92db-5c30ff6d91e1.png)

![image](https://user-images.githubusercontent.com/14271094/47625916-93a75200-db6b-11e8-9f75-2ddee9e122e7.png)

**Comment by starrybleu** [comment]
Any update on this? I guess this is related with stylesheet(css) that I’m not good at.

**Comment by ctxhou** [comment]
@starrybleu If this error message only happened in the demo page, I think the chances are the race condition when using react setState.

https://github.com/ctxhou/react-tabtab/blob/c682e91b63d24b43f833f8a2bc0ebd5da75a4de1/docs/components/Complicated.js#L38-L49

Based on your situation, you click the tab quickly, the race condition would happen. I will push and fix this demo bug.
Therefore I consider in your personal usage, if you use other way to handle the manipulation of the data, this bug should not happen, because the whole `react-tabtab` is API based, it never manipulate your data.


@kapilpipaliya So your problem is solved by implement your own close button?

**Comment by starrybleu** [comment]
Thank you for digging this problem. I found that closing action would happen when click close button quickly as you mentioned.
I also retrieve and manipulate my data from async API call.

Now, what I need is to implement debounce on click the close button before it turns out draggable context.

Thanks.

**Comment by kapilpipaliya** [comment]
My own close button solved the problem.
I tested on your demo site, sometimes drag and drop is not working.
https://i.imgur.com/MGhCziI.gif

**Comment by kapilpipaliya** [comment]
sometimes close button still not working on demo too.

**Comment by kapilpipaliya** [comment]
If I long press the close button, its not working.

**Comment by kapilpipaliya** [comment]
![gif-2018-11-27-201605](https://user-images.githubusercontent.com/13032024/49090412-a94f8a80-f283-11e8-892f-6f346886cca4.gif)
I really dont know how to solve it. Please help me.

**Comment by starrybleu** [comment]
@kapilpipaliya My front-end co-developer made a workaround as below.
```js
  componentDidUpdate() {
    [...document.getElementsByClassName('react-contextmenu-wrapper')].forEach((element) => {
      element.nextElementSibling.onmousedown = (e) => e.stopPropagation()
    })
  }
```

**Comment by willvoicebase** [comment]
I had this problem too. I fixed it by doing this:
1 - duplicate 2 files from the repo: DragTabList and SortMethod. I converted these files to standard components - they used this thing called 'flow' in their repo, I stripped it out.
2 - install 'react-sortable-hoc' in my repo
3 - I changed 'pressDelay' in DragTabList to '200' instead of '100' - this is actually the whole problem. For some reason, 100 was being completely ignored, but 200 does the trick. Here are the contents of the files:

DragTabList:
```
import React from 'react';
import SortMethod from './SortMethod';
import {SortableContainer} from 'react-sortable-hoc';
import { TabList } from 'react-tabtab';

const DragTabContainer = SortableContainer(({children, ...props}) => {
  return (
    <TabList {...props}>
      {children}
    </TabList>
  );
});

export default class DragTabList extends SortMethod {
  render() {
    const {children, ...props} = this.props;
    return (
      <DragTabContainer onSortEnd={this.onSortEnd}
                        axis='x'
                        lockAxis='x'
                        // if no pressDelay, close button cannot be triggered,
                        // because it would always treat click as dnd action
                        pressDelay={200}
                        {...props}>
        {children}
      </DragTabContainer>
    );
  }
}

DragTabList.displayName = 'DragTabList';
```

SortMethod:
```
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';

class SortMethod extends PureComponent {
  constructor(props) {
    super(props);
    this.onSortEnd = this.onSortEnd.bind(this);
  }

  onSortEnd({oldIndex, newIndex}) {
    const {activeIndex, handleTabChange, handleTabSequence} = this.props;
    if (oldIndex === newIndex) {
      if (activeIndex !== oldIndex) {
        handleTabChange(oldIndex);
      }
    } else {
      handleTabSequence({oldIndex, newIndex});
    }
  }
}

SortMethod.propTypes = {
  handleTabChange: PropTypes.func,
  handleTabSequence: PropTypes.func,
  activeIndex: PropTypes.number,
};

export default SortMethod;
```
